CREATE VIEW PassengersInfo
AS
    SELECT DISTINCT P.NAME AS PASSENGER_NAME, T.FLIGHTNUM AS FLIGHT, P.TYPE
FROM PASSENGERS P, TICKETS T
WHERE P.EMAIL = T.EMAIL;

--All employee names who works at gates
CREATE VIEW GateInfo
AS
    SELECT E.NAME AS EMPLOYEE_NAME, E.POSITION AS LEVEL, G.TYPE AS WORKS_AT, G.FLIGHTNUM AS FLIGHT
FROM EMPLOYEE E, GATE G
WHERE E.NUMBER=G.EMPLOYEENUM;