CREATE TABLE TERMINAL(
    NAME CHAR(1) NOT NULL PRIMARY KEY
);

CREATE TABLE FLIGHTS(
    NUMBER CHAR(8) NOT NULL PRIMARY KEY,
    COMPANY VARCHAR(50) NOT NULL,
    TYPE CHAR(1) CHECK(TYPE IN ('D','A')),
    TIME TIME,
    STARTPOINT VARCHAR(40),
    ENDPOINT VARCHAR(40),
    TERMINALNAME CHAR(1),
    FOREIGN KEY (TERMINALNAME) REFERENCES TERMINAL(NAME)
);

CREATE TABLE EMPLOYEE(
    NUMBER INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    NAME VARCHAR(50) NOT NULL ,
    POSITION VARCHAR(20) NOT NULL,
    TERMINALNAME CHAR(1),
    FOREIGN KEY (TERMINALNAME) REFERENCES TERMINAL(NAME)
);

CREATE TABLE PASSPORTCONTROL (
    NUMBER CHAR(3) NOT NULL PRIMARY KEY CHECK ( NUMBER LIKE('P_%') ),
    TYPE CHAR(8)  NOT NULL CHECK (LOWER(TYPE) LIKE 'passport'),
    EMPLOYEENUM INT,
    FOREIGN KEY (EMPLOYEENUM)REFERENCES EMPLOYEE(NUMBER)
);

CREATE TABLE GATE(
    NUMBER CHAR(3) NOT NULL PRIMARY KEY CHECK ( NUMBER LIKE('G_%') ),
    TYPE CHAR(4) NOT NULL CHECK (LOWER(TYPE) LIKE 'gate'),
    FLIGHTNUM CHAR(8) ,
    EMPLOYEENUM INT,
    FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHTS(NUMBER),
    FOREIGN KEY (EMPLOYEENUM)REFERENCES EMPLOYEE(NUMBER)
);

CREATE TABLE DESK(
    NUMBER CHAR(3) NOT NULL PRIMARY KEY CHECK ( NUMBER LIKE('D_%')) ,
    TYPE CHAR(4) NOT NULL CHECK (LOWER(TYPE) LIKE 'desk'),
    EMPLOYEENUM INT,
    FLIGHTNUM CHAR(8),
    FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHTS(NUMBER),
    FOREIGN KEY (EMPLOYEENUM)REFERENCES EMPLOYEE(NUMBER)
);



CREATE TABLE PASSENGERS(
    EMAIL CHAR(30) NOT NULL PRIMARY KEY CHECK(EMAIL LIKE '_%@_%.__%'),
    NAME VARCHAR(50) NOT NULL,
    TYPE CHAR(1) CHECK(TYPE IN ('D','A'))
);

CREATE TABLE TICKETS(
    UNIQUENUM INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 2022000 INCREMENT BY 1),
    EMPLOYEENUM INT NOT NULL ,
    EMAIL VARCHAR(30) NOT NULL ,
    FLIGHTNUM CHAR(8) NOT NULL ,
    FOREIGN KEY (EMPLOYEENUM) REFERENCES EMPLOYEE(NUMBER),
    FOREIGN KEY (EMAIL) REFERENCES PASSENGERS(EMAIL),
    FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHTS(NUMBER)
);